### ISSUE TITLE
Column 'username_id' cannot be null

### ISSUE THREAD

**Issue by viet** [greatman/craftconomy3#104]
I got this everytime a player logs in. Some new players get error when typing /money:
[CODE][01:08:08 INFO]: UUID of player EvgenDY is 92e271d5-0db1-4cea-a0fc-88c22099b211
[01:08:09 WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'username_id' cannot be null
[01:08:09 WARN]:        at sun.reflect.GeneratedConstructorAccessor150.newInstance(Unknown Source)
[01:08:09 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[01:08:09 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[01:08:09 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
[01:08:09 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:387)
[01:08:09 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:934)
[01:08:09 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3870)
[01:08:09 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3806)
[01:08:09 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2470)
[01:08:09 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2617)
[01:08:09 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2550)
[01:08:09 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
[01:08:09 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
[01:08:09 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009)
[01:08:09 WARN]:        at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5094)
[01:08:09 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1994)
[01:08:09 WARN]:        at com.greatmancode.com.zaxxer.libs.hikari.proxy.PreparedStatementProxy.executeUpdate(PreparedStatementProxy.java:61)
[01:08:09 WARN]:        at com.greatmancode.com.zaxxer.libs.hikari.proxy.PreparedStatementJavassistProxy.executeUpdate(PreparedStatementJavassistProxy.java)
[01:08:09 WARN]:        at com.greatmancode.craftconomy3.storage.sql.SQLStorageEngine.getAccount(SQLStorageEngine.java:114)
[01:08:09 WARN]:        at com.greatmancode.craftconomy3.storage.StorageEngine.getAccount(StorageEngine.java:54)
[01:08:09 WARN]:        at com.greatmancode.craftconomy3.account.AccountManager.getAccount(AccountManager.java:54)
[01:08:09 WARN]:        at com.greatmancode.craftconomy3.events.EventManager.playerJoinEvent(EventManager.java:54)
[01:08:09 WARN]:        at sun.reflect.GeneratedMethodAccessor95.invoke(Unknown Source)
[01:08:09 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:08:09 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[01:08:09 WARN]:        at com.greatmancode.craftconomy3.tools.events.ListenerRegistration.callEvent(ListenerRegistration.java:40)
[01:08:09 WARN]:        at com.greatmancode.craftconomy3.tools.events.EventManager.callEvent(EventManager.java:66)
[01:08:09 WARN]:        at com.greatmancode.craftconomy3.tools.events.bukkit.PlayerJoinEventListener.onPlayerJoin(PlayerJoinEventListener.java:32)
[01:08:09 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor59.execute(Unknown Source)
[01:08:09 WARN]:        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44)
[01:08:09 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[01:08:09 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[01:08:09 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
[01:08:09 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
[01:08:09 WARN]:        at net.minecraft.server.v1_10_R1.PlayerList.onPlayerJoin(PlayerList.java:356)
[01:08:09 WARN]:        at net.minecraft.server.v1_10_R1.PlayerList.a(PlayerList.java:175)
[01:08:09 WARN]:        at net.minecraft.server.v1_10_R1.LoginListener.b(LoginListener.java:144)
[01:08:09 WARN]:        at net.minecraft.server.v1_10_R1.LoginListener.E_(LoginListener.java:54)
[01:08:09 WARN]:        at net.minecraft.server.v1_10_R1.NetworkManager.a(NetworkManager.java:233)
[01:08:09 WARN]:        at net.minecraft.server.v1_10_R1.ServerConnection.c(ServerConnection.java:152)
[01:08:09 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:886)
[01:08:09 WARN]:        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404)
[01:08:09 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:725)
[01:08:09 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:624)
[01:08:09 WARN]:        at java.lang.Thread.run(Thread.java:745)
[/CODE]

[CODE][04:24:16 INFO]: NinaGillespie issued server command: /money
[04:24:16 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'money' in plugin Craftconomy3 v3.3-e72ac42-trv178
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.10.2.jar:git-Paper-837]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.10.2.jar:git-Paper-837]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:665) ~[patched_1.10.2.jar:git-Paper-837]
        at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1389) [patched_1.10.2.jar:git-Paper-837]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1194) [patched_1.10.2.jar:git-Paper-837]
        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.10.2.jar:git-Paper-837]
        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched_1.10.2.jar:git-Paper-837]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.10.2.jar:git-Paper-837]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [patched_1.10.2.jar:git-Paper-837]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:791) [patched_1.10.2.jar:git-Paper-837]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-837]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:725) [patched_1.10.2.jar:git-Paper-837]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:624) [patched_1.10.2.jar:git-Paper-837]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
        at com.greatmancode.craftconomy3.commands.money.MainCommand.execute(MainCommand.java:31) ~[?:?]
        at com.greatmancode.craftconomy3.tools.commands.SubCommand.execute(SubCommand.java:69) ~[?:?]
        at com.greatmancode.craftconomy3.tools.commands.bukkit.BukkitCommandReceiver.onCommand(BukkitCommandReceiver.java:51) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.10.2.jar:git-Paper-837]
        ... 15 more
[/CODE]

Do you know how to fix it?

**Comment by pavog** [comment]
Kamino cloned this issue to [pavog/craftconomy3](https://github.com/pavog/craftconomy3/issues/11)
