### ISSUE TITLE
Failed to load class "org.slf4j.impl.StaticLoggerBinder"

### ISSUE THREAD

**Issue by TheoRetisch1** [greatman/craftconomy3#111]
Everytime I start the server i get this error.
https://pastebin.com/en6r07b6
[PaperSpigiot 1.12 #1008, craftconomy3-3.3.1-20170608.230020-18.jar]

**Comment by EvilOlaf** [comment]
Confirmed.
```
...
08:04:55] [Server thread/INFO]: [Craftconomy3] Loading commands
[08:04:55] [Server thread/INFO]: [Craftconomy3] Loading the Database Manager
[08:04:55] [Server thread/WARN]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[08:04:55] [Server thread/WARN]: SLF4J: Defaulting to no-operation (NOP) logger implementation
[08:04:55] [Server thread/WARN]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[08:04:55] [Server thread/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead
[08:04:55] [Server thread/WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[08:04:55] [Server thread/WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[08:04:55] [Server thread/WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[08:04:55] [Server thread/WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[08:04:55] [Server thread/WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[08:04:55] [Server thread/WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:382)
[08:04:55] [Server thread/WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
[08:04:55] [Server thread/WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[08:04:55] [Server thread/WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[08:04:55] [Server thread/WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[08:04:55] [Server thread/WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[08:04:55] [Server thread/WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
[08:04:55] [Server thread/WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
[08:04:55] [Server thread/WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407)
[08:04:55] [Server thread/WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325)
[08:04:55] [Server thread/WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310)
[08:04:55] [Server thread/WARN]:        at com.greatmancode.com.zaxxer.libs.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[08:04:55] [Server thread/WARN]:        at com.greatmancode.com.zaxxer.libs.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[08:04:55] [Server thread/WARN]:        at com.greatmancode.craftconomy3.storage.sql.MySQLEngine.<init>(MySQLEngine.java:83)
[08:04:55] [Server thread/WARN]:        at com.greatmancode.craftconomy3.storage.StorageHandler.<init>(StorageHandler.java:40)
[08:04:55] [Server thread/WARN]:        at com.greatmancode.craftconomy3.Common.initialiseDatabase(Common.java:397)
[08:04:55] [Server thread/WARN]:        at com.greatmancode.craftconomy3.Common.onEnable(Common.java:144)
[08:04:55] [Server thread/WARN]:        at com.greatmancode.craftconomy3.tools.interfaces.BukkitLoader.onEnable(BukkitLoader.java:49)
[08:04:55] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[08:04:55] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[08:04:55] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[08:04:55] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[08:04:55] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[08:04:55] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
[08:04:55] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
[08:04:55] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
[08:04:55] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
[08:04:55] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[08:04:55] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:748)
[08:04:55] [Server thread/INFO]: [Craftconomy3] Database Manager Loaded!
[08:04:55] [Server thread/INFO]: [Craftconomy3] Loading the Currency manager.
...
```

3.3.1-d99cf63-trv200
Spigot 1.8.8

**Comment by Aztorius** [comment]
Fixed in latest version on master. Wait for a new official fix release.
Also @EvilOlaf you have another issue : 
`com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead`
You may want to open another ticket.
