### ISSUE TITLE
Error when starting the server

### ISSUE THREAD

**Issue by stefvanschie** [greatman/craftconomy3#119]
I recently installed CraftConomy 3.3.1 (like two days ago) and got the following error:

> [12:02:43] [Server thread/ERROR]: Error occurred while enabling Craftconomy3 v3.3.1-d99cf63-trv200 (Is it up to date?)
com.greatmancode.com.zaxxer.libs.hikari.pool.HikariPool$PoolInitializationException: Exception during pool initialization: HikariPool-0 - Connection is not available, request timed out after 5001ms.
	at com.greatmancode.com.zaxxer.libs.hikari.pool.HikariPool.initializeConnections(HikariPool.java:526) ~[?:?]
	at com.greatmancode.com.zaxxer.libs.hikari.pool.HikariPool.<init>(HikariPool.java:136) ~[?:?]
	at com.greatmancode.com.zaxxer.libs.hikari.HikariDataSource.<init>(HikariDataSource.java:71) ~[?:?]
	at com.greatmancode.craftconomy3.storage.sql.H2Engine.<init>(H2Engine.java:41) ~[?:?]
	at com.greatmancode.craftconomy3.storage.StorageHandler.<init>(StorageHandler.java:36) ~[?:?]
	at com.greatmancode.craftconomy3.Common.initialiseDatabase(Common.java:397) ~[?:?]
	at com.greatmancode.craftconomy3.Common.onEnable(Common.java:144) ~[?:?]
	at com.greatmancode.craftconomy3.tools.interfaces.BukkitLoader.onEnable(BukkitLoader.java:49) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.jar:git-Spigot-7228328-6659ddf]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:378) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.sql.SQLTransientConnectionException: HikariPool-0 - Connection is not available, request timed out after 5001ms.
	at com.greatmancode.com.zaxxer.libs.hikari.pool.HikariPool.getConnection(HikariPool.java:195) ~[?:?]
	at com.greatmancode.com.zaxxer.libs.hikari.pool.HikariPool.getConnection(HikariPool.java:147) ~[?:?]
	at com.greatmancode.com.zaxxer.libs.hikari.pool.HikariPool.initializeConnections(HikariPool.java:510) ~[?:?]
	... 18 more

(formatting messed up a bit, sorry about that)
I don't know I forgot to do something, or if it's my own plugin (it didn't mention any of my plugin in the error, so...), but I thought I'd let you know about this anyway. This happened while starting the server.

**Comment by greatman** [comment]
Exception during pool initialization: HikariPool-0 - Connection is not available, request timed out after 5001ms.

Craftconomy is not able to connect to the database backend. Wrong settings in the config.yml maybe?

**Comment by stefvanschie** [comment]
I've never setup a database for this plugin. Did CraftConomy always require a database? Because it never gave errors before.
