### ISSUE TITLE
Exception on Server Start

### ISSUE THREAD

**Issue by Ringwid** [greatman/craftconomy3#130]
This error occurs every time I start my server.
`com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead
       at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
       at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
       at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
       at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
       at com.mysql.jdbc.Util.getInstance(Util.java:408)
       at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
       at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
       at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
       at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
       at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
       at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2487)
       at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
       at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
       at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
       at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
       at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
       at com.greatmancode.com.zaxxer.libs.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
       at com.greatmancode.com.zaxxer.libs.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
       at com.greatmancode.craftconomy3.storage.sql.MySQLEngine.<init>(MySQLEngine.java:83)
       at com.greatmancode.craftconomy3.storage.StorageHandler.<init>(StorageHandler.java:40)
       at com.greatmancode.craftconomy3.Common.initialiseDatabase(Common.java:397)
       at com.greatmancode.craftconomy3.Common.onEnable(Common.java:144)
       at com.greatmancode.craftconomy3.tools.interfaces.BukkitLoader.onEnable(BukkitLoader.java:49)
       at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
       at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
       at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
       at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:384)
       at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:333)
       at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
       at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
       at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
       at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292)
       at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
       at java.lang.Thread.run(Thread.java:748)`

**Comment by JohOply** [comment]
Solution here https://github.com/greatman/craftconomy3/issues/132
