### ISSUE TITLE
CraftConomy & Vault Issue

### ISSUE THREAD

**Issue by SirWilli** [greatman/craftconomy3#22]
hey,

sometimes my log get spammed with this errors if I have BungeeTabListPlus and CraftConomy installed.

```
[20:51:12 WARN]: [BungeeTabListPlus_BukkitBridge] ?cAn internal error occured! Please send the following stacktrace to the developer in order to help resolving the problem
java.lang.NullPointerException
>       at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.getBalance(Economy_Craftconomy3.java:287) ~[Vault-1.4.2-C.jar:?]
>       at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.getBalance(Economy_Craftconomy3.java:123) ~[Vault-1.4.2-C.jar:?]
>       at codecrafter47.bungeetablistplus.bukkitbridge.informationhooks.VaultHook.getInformation(VaultHook.java:110) [BungeeTabListPlus_BukkitBridge-7.jar:?]
>       at codecrafter47.bungeetablistplus.bukkitbridge.PlayerInformationUpdateTask.update(PlayerInformationUpdateTask.java:95) [BungeeTabListPlus_BukkitBridge-7.jar:?]
>       at codecrafter47.bungeetablistplus.bukkitbridge.PlayerInformationUpdateTask.run(PlayerInformationUpdateTask.java:61) [BungeeTabListPlus_BukkitBridge-7.jar:?]
>       at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) [CraftTask.class:1.7.10-1448.124]
>       at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [CraftAsyncTask.class:1.7.10-1448.124]
>       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_76]
>       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_76]
>       at java.lang.Thread.run(Thread.java:745) [?:1.7.0_76]
 
```

**Comment by greatman** [comment]
What version of Craftconomy you are running? Seems to be a new CC3 version with a old Vault version.

**Comment by SirWilli** [comment]
Craftconomy3 version 3.2.1-13814c0-trv139
 Vault version 1.4.2

**Comment by greatman** [comment]
Try Vault 1.5.2 or higher

**Comment by SirWilli** [comment]
I can't as it is for 1.8 and I'm still on 1.7.10 :/
