### ISSUE TITLE
NPE onJoin

### ISSUE THREAD

**Issue by idkw** [greatman/craftconomy3#24]
Here's a NPE I got using spigot

```
[19:05:28] [Thread-110/INFO]: UUID of player val59000 is 5c7337d5-903e-4e13-9061-06b4384074ea
[19:05:28] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[19:05:28] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
[19:05:28] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:05:28] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[19:05:28] [Server thread/WARN]: 	at com.greatmancode.craftconomy3.tools.events.ListenerRegistration.callEvent(ListenerRegistration.java:40)
[19:05:28] [Server thread/WARN]: 	at com.greatmancode.craftconomy3.tools.events.EventManager.callEvent(EventManager.java:66)
[19:05:28] [Server thread/WARN]: 	at com.greatmancode.craftconomy3.tools.events.bukkit.PlayerJoinEventListener.onPlayerJoin(PlayerJoinEventListener.java:31)
[19:05:28] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor62.invoke(Unknown Source)
[19:05:28] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:05:28] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[19:05:28] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[19:05:28] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[19:05:28] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[19:05:28] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[19:05:28] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:296)
[19:05:28] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:156)
[19:05:28] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144)
[19:05:28] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54)
[19:05:28] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231)
[19:05:28] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148)
[19:05:28] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:817)
[19:05:28] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367)
[19:05:28] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657)
[19:05:28] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560)
[19:05:28] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[19:05:28] [Server thread/WARN]: Caused by: java.lang.NullPointerException
[19:05:28] [Server thread/WARN]: 	at com.greatmancode.craftconomy3.events.EventManager.playerJoinEvent(EventManager.java:40)
[19:05:28] [Server thread/WARN]: 	... 24 more
```

**Comment by greatman** [comment]
Try the 3.3 versions.
