### ISSUE TITLE
Something is wrong in my server

### ISSUE THREAD

**Issue by a08381** [greatman/craftconomy3#27]
Two Server use a same database
Spigot 1.8.7 , Vault 1.5.3 , CraftConomy3.3

One Server :

```
[14:52:22 WARN]: [BungeeTabListPlus_BukkitBridge] §cAn internal error occured!
Please send the following stacktrace to the developer in order to help resolving the problem
java.lang.NullPointerException
        at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.getBalance(Economy_Craftconomy3.java:278) ~[Vault.jar:?]
        at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.getBalance(Economy_Craftconomy3.java:120) ~[Vault.jar:?]
        at codecrafter47.bungeetablistplus.bukkitbridge.informationhooks.VaultHook.getInformation(VaultHook.java:102) [BungeeTabListPlus_BukkitBridge-7.jar:?]
        at codecrafter47.bungeetablistplus.bukkitbridge.PlayerInformationUpdateTask.update(PlayerInformationUpdateTask.java:91) [BungeeTabListPlus_BukkitBridge-7.jar:?]
        at codecrafter47.bungeetablistplus.bukkitbridge.PlayerInformationUpdateTask.run(PlayerInformationUpdateTask.java:57) [BungeeTabListPlus_BukkitBridge-7.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.8.7-R0.1-SNAPSHOT.jar:git-Spigot-44c59bf-1880a9c]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.7-R0.1-SNAPSHOT.jar:git-Spigot-44c59bf-1880a9c]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:726) [spigot-1.8.7-R0.1-SNAPSHOT.jar:git-Spigot-44c59bf-1880a9c]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot-1.8.7-R0.1-SNAPSHOT.jar:git-Spigot-44c59bf-1880a9c]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot-1.8.7-R0.1-SNAPSHOT.jar:git-Spigot-44c59bf-1880a9c]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot-1.8.7-R0.1-SNAPSHOT.jar:git-Spigot-44c59bf-1880a9c]
        at java.lang.Thread.run(Unknown Source) [?:1.7.0_79]
```

Another Server :

```
[14:41:43 WARN]: Unexpected exception while parsing console command "money give lt_lentong 100"
org.bukkit.command.CommandException: Unhandled exception executing command 'money' in plugin Craftconomy3 v3.3-e72ac42-trv178
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.7-R0.1-SNAPSHOT.jar:git-Spigot-44c59bf-1880a9c]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.7-R0.1-SNAPSHOT.jar:git-Spigot-44c59bf-1880a9c]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:642) ~[spigot-1.8.7-R0.1-SNAPSHOT.jar:git-Spigot-44c59bf-1880a9c]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:628) [spigot-1.8.7-R0.1-SNAPSHOT.jar:git-Spigot-44c59bf-1880a9c]
        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:404) [spigot-1.8.7-R0.1-SNAPSHOT.jar:git-Spigot-44c59bf-1880a9c]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:368) [spigot-1.8.7-R0.1-SNAPSHOT.jar:git-Spigot-44c59bf-1880a9c]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot-1.8.7-R0.1-SNAPSHOT.jar:git-Spigot-44c59bf-1880a9c]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot-1.8.7-R0.1-SNAPSHOT.jar:git-Spigot-44c59bf-1880a9c]
        at java.lang.Thread.run(Unknown Source) [?:1.7.0_79]
Caused by: java.lang.NullPointerException
        at com.greatmancode.craftconomy3.commands.money.GiveCommand.execute(GiveCommand.java:53) ~[?:?]
        at com.greatmancode.craftconomy3.tools.commands.SubCommand.execute(SubCommand.java:69) ~[?:?]
        at com.greatmancode.craftconomy3.tools.commands.bukkit.BukkitCommandReceiver.onCommand(BukkitCommandReceiver.java:51) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.7-R0.1-SNAPSHOT.jar:git-Spigot-44c59bf-1880a9c]
        ... 8 more
```

**Comment by greatman** [comment]
Is craftconomy configured (Ran the setup wizard) ? I usually see those errors in that case or CC3 failed to load properly.
