### ISSUE TITLE
SQLite error 3.3

### ISSUE THREAD

**Issue by greatman** [greatman/craftconomy3#35]
[02:58:49] [Server thread/INFO]: [Craftconomy3] Enabling Craftconomy3 v3.3-e72ac42-trv178
[02:58:49] [Server thread/INFO]: [Craftconomy3] Starting up!
[02:58:49] [Server thread/INFO]: [Craftconomy3] Loading the Configuration
[02:58:50] [Server thread/INFO]: [Craftconomy3] Loading listeners.
[02:58:50] [Server thread/INFO]: [Craftconomy3] Loading commands
[02:58:50] [Server thread/INFO]: [Craftconomy3] Loading the Database Manager
[02:58:50] [Server thread/WARN]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[02:58:50] [Server thread/WARN]: SLF4J: Defaulting to no-operation (NOP) logger implementation
[02:58:50] [Server thread/WARN]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[02:58:51] [Server thread/ERROR]: Error occurred while enabling Craftconomy3 v3.3-e72ac42-trv178 (Is it up to date?)
com.greatmancode.com.zaxxer.libs.hikari.pool.PoolInitializationException: Exception during pool initialization
        at com.greatmancode.com.zaxxer.libs.hikari.pool.BaseHikariPool.initializeConnections(BaseHikariPool.java:542) ~[?:?]
        at com.greatmancode.com.zaxxer.libs.hikari.pool.BaseHikariPool.<init>(BaseHikariPool.java:171) ~[?:?]
        at com.greatmancode.com.zaxxer.libs.hikari.pool.HikariPool.<init>(HikariPool.java:60) ~[?:?]
        at com.greatmancode.com.zaxxer.libs.hikari.pool.HikariPool.<init>(HikariPool.java:48) ~[?:?]
        at com.greatmancode.com.zaxxer.libs.hikari.HikariDataSource.<init>(HikariDataSource.java:80) ~[?:?]
        at com.greatmancode.craftconomy3.storage.sql.SQLiteEngine.<init>(SQLiteEngine.java:56) ~[?:?]
        at com.greatmancode.craftconomy3.storage.StorageHandler.<init>(StorageHandler.java:44) ~[?:?]
        at com.greatmancode.craftconomy3.Common.initialiseDatabase(Common.java:393) ~[?:?]
        at com.greatmancode.craftconomy3.Common.onEnable(Common.java:143) ~[?:?]
        at com.greatmancode.craftconomy3.tools.interfaces.BukkitLoader.onEnable(BukkitLoader.java:49) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Bukkit-0a645a2]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:327) [spigot.jar:git-Bukkit-0a645a2]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [spigot.jar:git-Bukkit-0a645a2]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:341) [spigot.jar:git-Bukkit-0a645a2]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:313) [spigot.jar:git-Bukkit-0a645a2]
        at net.minecraft.server.v1_8_R2.MinecraftServer.r(MinecraftServer.java:408) [spigot.jar:git-Bukkit-0a645a2]
        at net.minecraft.server.v1_8_R2.MinecraftServer.k(MinecraftServer.java:374) [spigot.jar:git-Bukkit-0a645a2]
        at net.minecraft.server.v1_8_R2.MinecraftServer.a(MinecraftServer.java:329) [spigot.jar:git-Bukkit-0a645a2]
        at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:236) [spigot.jar:git-Bukkit-0a645a2]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:501) [spigot.jar:git-Bukkit-0a645a2]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: java.sql.SQLException: JDBC4 Connection.isValid() method not supported, connection test query must be configured
        at com.greatmancode.com.zaxxer.libs.hikari.pool.BaseHikariPool.addConnection(BaseHikariPool.java:441) ~[?:?]
        at com.greatmancode.com.zaxxer.libs.hikari.pool.BaseHikariPool.initializeConnections(BaseHikariPool.java:540) ~[?:?]
        ... 20 more

**Comment by kirkebarrett** [comment]
I have this exact same issue.  Am i missing something?

**Comment by tkausl** [comment]
Looks like a bug in hikari. Is there a config-option in hikari to set the test-query? `SELECT 1;` should work as test-query just fine

**Comment by tkausl** [comment]
See PR #38 
Unfortunately, i am not able to test it, if anyone of you could test this change and report back here or in the PR, this would be great.

**Comment by greatman** [comment]
Keeping this open for feedback on PR #38
