### ISSUE TITLE
NPE with /craftconomy reload

### ISSUE THREAD

**Issue by idkw** [greatman/craftconomy3#44]
I can't make change to the config because the reload command throw a NPE

```
[03:24:26 INFO]: val59000 issued server command: /craftconomy reload
>
[03:24:26 INFO]: [Craftconomy3] Closing the connection to the database.
>
[03:24:26 INFO]: [Craftconomy3] Starting up!
>
[03:24:26 INFO]: [Craftconomy3] Loading the Configuration
>
[03:24:26 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'craftconomy' in plugin Craftconomy3 v3.3-e72ac42-trv178
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.8.jar:git-Spigot-d97e08b-5e85956]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.8.jar:git-Spigot-d97e08b-5e85956]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:640) ~[spigot-1.8.8.jar:git-Spigot-d97e08b-5e85956]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8.jar:git-Spigot-d97e08b-5e85956]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-d97e08b-5e85956]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-d97e08b-5e85956]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-d97e08b-5e85956]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-d97e08b-5e85956]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_05]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_05]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-d97e08b-5e85956]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot-1.8.8.jar:git-Spigot-d97e08b-5e85956]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-d97e08b-5e85956]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot-1.8.8.jar:git-Spigot-d97e08b-5e85956]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot-1.8.8.jar:git-Spigot-d97e08b-5e85956]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_05]
Caused by: java.lang.NullPointerException
	at com.greatmancode.craftconomy3.Common.reloadPlugin(Common.java:207) ~[?:?]
	at com.greatmancode.craftconomy3.commands.config.ConfigReloadCommand.execute(ConfigReloadCommand.java:28) ~[?:?]
	at com.greatmancode.craftconomy3.tools.commands.SubCommand.execute(SubCommand.java:69) ~[?:?]
	at com.greatmancode.craftconomy3.tools.commands.bukkit.BukkitCommandReceiver.onCommand(BukkitCommandReceiver.java:51) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8.jar:git-Spigot-d97e08b-5e85956]
	... 15 more

````

I'm using 3.3.3 on Spigot 1.8.8

**Comment by TheGamesHawk2001** [comment]
Same

**Comment by JasonLamey** [comment]
Also having this issue.
