### ISSUE TITLE
/money set produces null error

### ISSUE THREAD

**Issue by AvatarAcid** [greatman/craftconomy3#47]
Fresh install of CC3. ccsetup completed with no errors.
Created a group for PvP world and assigned it.
Created a group for Survival world and assigned it.

in the survival world I ran: /money set AvatarAcid 1000 Dollar
checked my balance. all good.

warped to the PvP world and ran: /money set AvatarAcid 1000 Dollar

I got the following error when I did that. Restarted server, same error.

/money all shows 100 Dollars in the default group which I don't know how to get rid of, and shows 1,000 in the survival group which I set. Nothing in PvP group due to the error here:

[03:28:50 INFO]: AvatarAcid issued server command: /money set AvatarAcid 1000 Dollar
[03:28:50 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'money' in plugin Craftconomy3 v3.3-e72ac42-trv178

**Comment by greatman** [comment]
Need the full stacktrace. Only that line doesn't give me the exact error.

**Comment by AvatarAcid** [comment]
03:28:50] [Server thread/INFO]: AvatarAcid issued server command: /money set AvatarAcid 1000 Guilder
[03:28:50] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'money' in plugin Craftconomy3 v3.3-e72ac42-trv178
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-76236cb-62a2169]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-76236cb-62a2169]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-Spigot-76236cb-62a2169]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot.jar:git-Spigot-76236cb-62a2169]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot.jar:git-Spigot-76236cb-62a2169]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-76236cb-62a2169]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-76236cb-62a2169]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-76236cb-62a2169]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_45]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_45]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-76236cb-62a2169]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-76236cb-62a2169]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-76236cb-62a2169]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-76236cb-62a2169]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-76236cb-62a2169]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_45]
Caused by: java.lang.NullPointerException
	at com.greatmancode.craftconomy3.account.Account.getWorldGroupOfPlayerCurrentlyIn(Account.java:305) ~[?:?]
	at com.greatmancode.craftconomy3.commands.money.SetCommand.execute(SetCommand.java:44) ~[?:?]
	at com.greatmancode.craftconomy3.tools.commands.SubCommand.execute(SubCommand.java:69) ~[?:?]
	at com.greatmancode.craftconomy3.tools.commands.bukkit.BukkitCommandReceiver.onCommand(BukkitCommandReceiver.java:51) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-76236cb-62a2169]
	... 15 more
