### ISSUE TITLE
Plugin Setup without /ccsetup not Possible

### ISSUE THREAD

**Issue by SirWilli** [greatman/craftconomy3#51]
hey,

if I copy the configured config from a other server and start the server with it it will not create user accounts. If I run /money it does throw this error:
```
[02:43:21] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'money' in plugin Craftconomy3 v3.2.1-13814c0-trv139
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:1.7.10-1492.152]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:1.7.10-1492.152]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717) ~[CraftServer.class:1.7.10-1492.152]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1317) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1099) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.NullPointerException
	at com.greatmancode.craftconomy3.storage.sql.SQLStorageEngine.getAccount(SQLStorageEngine.java:107) ~[?:?]
	at com.greatmancode.craftconomy3.storage.StorageEngine.getAccount(StorageEngine.java:54) ~[?:?]
	at com.greatmancode.craftconomy3.account.AccountManager.getAccount(AccountManager.java:54) ~[?:?]
	at com.greatmancode.craftconomy3.commands.money.MainCommand.execute(MainCommand.java:30) ~[?:?]
	at com.greatmancode.craftconomy3.tools.commands.SubCommand.execute(SubCommand.java:69) ~[?:?]
	at com.greatmancode.craftconomy3.tools.commands.bukkit.BukkitCommandReceiver.onCommand(BukkitCommandReceiver.java:51) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:1.7.10-1492.152]
	... 13 more
```

The only way I  could get it to work is to use the /ccsetup command. Which is annoying if you need todo it for multiple servers. 
Is there any way this can be fixed/changed?

**Comment by greatman** [comment]
If you only copy the config file and you don't use a h2 database, it will crash since the whole cc3 configuration is in the database. There's quicksetup in the config file to generate a database file with settings defined in it.

**Comment by SirWilli** [comment]
Hm, I already have that. Does Setup: false need to be true too so the quicksetup works?

**Comment by MineHeads** [comment]
Read the plugin page very good and youll find yous answors! Its a bit complicated but if you read all the text very well its so easy!!

**Comment by MineHeads** [comment]
And btw. I think the settup is a positive thing. Its easy and a quicker then the config file. If you do it with /ccsetup and you set the right permissions you can set this thing up in 5 min!

**Comment by SirWilli** [comment]
I don't see any information about this on the plugin page or github wiki. It only says use /ccsetup

**Comment by MineHeads** [comment]
Then use /ccsetup if you want no errors and problems
