### ISSUE TITLE
Multiple balances Mysql error - any help please

### ISSUE THREAD

**Issue by random1167** [greatman/craftconomy3#53]
[23:08:18 INFO]: rex issued server command: /money pay Jynx 1
[23:08:18 WARN]: java.sql.SQLException: Subquery returns more than 1 row
[23:08:18 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
[23:08:18 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[23:08:18 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[23:08:18 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[23:08:18 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[23:08:18 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
[23:08:18 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
[23:08:18 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407)
[23:08:18 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325)
[23:08:18 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310)
[23:08:18 WARN]:        at com.greatmancode.com.zaxxer.libs.hikari.proxy.PreparedStatementProxy.executeUpdate(PreparedStatementProxy.java:61)
[23:08:18 WARN]:        at com.greatmancode.com.zaxxer.libs.hikari.proxy.PreparedStatementJavassistProxy.executeUpdate(PreparedStatementJavassistProxy.java)
[23:08:18 WARN]:        at com.greatmancode.craftconomy3.storage.sql.SQLStorageEngine.saveLog(SQLStorageEngine.java:197)
[23:08:18 WARN]:        at com.greatmancode.craftconomy3.storage.sql.SQLStorageEngine.saveLog(SQLStorageEngine.java:178)
[23:08:18 WARN]:        at com.greatmancode.craftconomy3.Common.writeLog(Common.java:503)
[23:08:18 WARN]:        at com.greatmancode.craftconomy3.account.Account.withdraw(Account.java:214)
[23:08:18 WARN]:        at com.greatmancode.craftconomy3.commands.money.PayCommand.execute(PayCommand.java:46)
[23:08:18 WARN]:        at com.greatmancode.craftconomy3.tools.commands.SubCommand.execute(SubCommand.java:69)
[23:08:18 WARN]:        at com.greatmancode.craftconomy3.tools.commands.bukkit.BukkitCommandReceiver.onCommand(BukkitCommandReceiver.java:51)
[23:08:18 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[23:08:18 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[23:08:18 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[23:08:18 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1165)
[23:08:18 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1000)
[23:08:18 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[23:08:18 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[23:08:18 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[23:08:18 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[23:08:18 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[23:08:18 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[23:08:18 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:772)
[23:08:18 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[23:08:18 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:711)
[23:08:18 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:614)
[23:08:18 WARN]:        at java.lang.Thread.run(Thread.java:745)

**Comment by random1167** [comment]
so far its only coming from 1 player and and he has 2 balances 
http://i.imgur.com/T6yXYLg.jpg

**Comment by random1167** [comment]
deleted the account,solved

**Comment by random1167** [comment]
Same issue, and i dont know how to fix it ive deleted the players account
rex1167 issued server command: /money pay jakeg42001 1
[15:10:09 WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'username_id' cannot be null
[15:10:09 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[15:10:09 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
[15:10:09 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[15:10:09 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
[15:10:09 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[15:10:09 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:382)
[15:10:09 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
[15:10:09 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[15:10:09 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[15:10:09 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[15:10:09 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[15:10:09 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
[15:10:09 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
[15:10:09 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407)
[15:10:09 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325)
[15:10:09 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310)
[15:10:09 WARN]:        at com.greatmancode.com.zaxxer.libs.hikari.proxy.PreparedStatementProxy.executeUpdate(PreparedStatementProxy.java:61)
[15:10:09 WARN]:        at com.greatmancode.com.zaxxer.libs.hikari.proxy.PreparedStatementJavassistProxy.executeUpdate(PreparedStatementJavassistProxy.java)
[15:10:09 WARN]:        at com.greatmancode.craftconomy3.storage.sql.SQLStorageEngine.setBalance(SQLStorageEngine.java:368)
[15:10:09 WARN]:        at com.greatmancode.craftconomy3.account.Account.deposit(Account.java:169)
[15:10:09 WARN]:        at com.greatmancode.craftconomy3.commands.money.PayCommand.execute(PayCommand.java:47)
[15:10:09 WARN]:        at com.greatmancode.craftconomy3.tools.commands.SubCommand.execute(SubCommand.java:69)
[15:10:09 WARN]:        at com.greatmancode.craftconomy3.tools.commands.bukkit.BukkitCommandReceiver.onCommand(BukkitCommandReceiver.java:51)
[15:10:09 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[15:10:09 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[15:10:09 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[15:10:09 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1165)
[15:10:09 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1000)
[15:10:09 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[15:10:09 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[15:10:09 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[15:10:09 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
[15:10:09 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
[15:10:09 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[15:10:09 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:772)
[15:10:09 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[15:10:09 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:711)
[15:10:09 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:614)
[15:10:09 WARN]:        at java.lang.Thread.run(Thread.java:745)
[15:12:27 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'money' in plugin Craftconomy3 v3.3-e72ac42-trv178
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[paperspigot.jar:git-PaperSpigot-5be55c3-18fbb24]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[paperspigot.jar:git-PaperSpigot-5be55c3-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[paperspigot.jar:git-PaperSpigot-5be55c3-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1165) [paperspigot.jar:git-PaperSpigot-5be55c3-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1000) [paperspigot.jar:git-PaperSpigot-5be55c3-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [paperspigot.jar:git-PaperSpigot-5be55c3-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [paperspigot.jar:git-PaperSpigot-5be55c3-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [paperspigot.jar:git-PaperSpigot-5be55c3-18fbb24]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_91]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [paperspigot.jar:git-PaperSpigot-5be55c3-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:772) [paperspigot.jar:git-PaperSpigot-5be55c3-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [paperspigot.jar:git-PaperSpigot-5be55c3-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:711) [paperspigot.jar:git-PaperSpigot-5be55c3-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:614) [paperspigot.jar:git-PaperSpigot-5be55c3-18fbb24]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_91]
Caused by: com.greatmancode.craftconomy3.utils.BackendErrorException: Column 'username_id' cannot be null
        at com.greatmancode.craftconomy3.storage.sql.SQLStorageEngine.setBalance(SQLStorageEngine.java:373) ~[?:?]
        at com.greatmancode.craftconomy3.account.Account.deposit(Account.java:169) ~[?:?]
        at com.greatmancode.craftconomy3.commands.money.PayCommand.execute(PayCommand.java:47) ~[?:?]
        at com.greatmancode.craftconomy3.tools.commands.SubCommand.execute(SubCommand.java:69) ~[?:?]
        at com.greatmancode.craftconomy3.tools.commands.bukkit.BukkitCommandReceiver.onCommand(BukkitCommandReceiver.java:51) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[paperspigot.jar:git-PaperSpigot-5be55c3-18fbb24]
        ... 15 more

**Comment by random1167** [comment]
deleted the player account and the username from ESS and from playerdata
seems to be ok now
