### ISSUE TITLE
Converting from Essentials and getting less than half the data

### ISSUE THREAD

**Issue by Buckmanfu** [greatman/craftconomy3#65]
I am working on migrating away from Essentials completely.  When I convert the ccsetup, it registers 1400ish accounts and only converts just over 500. 

I'm getting this in the console when the conversion runs

2016-01-03 13:40:07 [WARN]      at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
2016-01-03 13:40:07 [WARN]      at org.h2.message.DbException.get(DbException.java:179)
2016-01-03 13:40:07 [WARN]      at org.h2.message.DbException.get(DbException.java:155)
2016-01-03 13:40:07 [WARN]      at org.h2.message.DbException.get(DbException.java:144)
2016-01-03 13:40:07 [WARN]      at org.h2.expression.Subquery.getValue(Subquery.java:41)
2016-01-03 13:40:07 [WARN]      at org.h2.command.dml.Insert.insertRows(Insert.java:143)
2016-01-03 13:40:07 [WARN]      at org.h2.command.dml.Insert.update(Insert.java:114)
2016-01-03 13:40:07 [WARN]      at org.h2.command.CommandContainer.update(CommandContainer.java:78)
2016-01-03 13:40:07 [WARN]      at org.h2.command.Command.executeUpdate(Command.java:254)
2016-01-03 13:40:07 [WARN]      at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:157)
2016-01-03 13:40:07 [WARN]      at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:143)
2016-01-03 13:40:07 [WARN]      at com.greatmancode.com.zaxxer.libs.hikari.proxy.PreparedStatementProxy.executeUpdate(PreparedStatementProxy.java:61)
2016-01-03 13:40:07 [WARN]      at com.greatmancode.com.zaxxer.libs.hikari.proxy.PreparedStatementJavassistProxy.executeUpdate(PreparedStatementJavassistProxy.java)
2016-01-03 13:40:07 [WARN]      at com.greatmancode.craftconomy3.storage.sql.SQLStorageEngine.saveImporterUsers(SQLStorageEngine.java:1080)
2016-01-03 13:40:07 [WARN]      at com.greatmancode.craftconomy3.converter.Converter.addAccountToString(Converter.java:167)
2016-01-03 13:40:07 [WARN]      at com.greatmancode.craftconomy3.converter.converters.Essentials.importData(Essentials.java:105)
2016-01-03 13:40:07 [WARN]      at com.greatmancode.craftconomy3.commands.setup.NewSetupConvertCommand.selectDb(NewSetupConvertCommand.java:121)
2016-01-03 13:40:07 [WARN]      at com.greatmancode.craftconomy3.commands.setup.NewSetupConvertCommand.selectConvert(NewSetupConvertCommand.java:143)
2016-01-03 13:40:07 [WARN]      at com.greatmancode.craftconomy3.commands.setup.NewSetupConvertCommand.execute(NewSetupConvertCommand.java:50)
2016-01-03 13:40:07 [WARN]      at com.greatmancode.craftconomy3.tools.commands.SubCommand.execute(SubCommand.java:69)
2016-01-03 13:40:07 [WARN]      at com.greatmancode.craftconomy3.tools.commands.bukkit.BukkitCommandReceiver.onCommand(BukkitCommandReceiver.java:51)
2016-01-03 13:40:07 [WARN]      at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
2016-01-03 13:40:07 [WARN]      at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
2016-01-03 13:40:07 [WARN]      at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
2016-01-03 13:40:07 [WARN]      at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
2016-01-03 13:40:07 [WARN]      at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
2016-01-03 13:40:07 [WARN]      at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
2016-01-03 13:40:07 [WARN]      at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
2016-01-03 13:40:07 [WARN]      at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
2016-01-03 13:40:07 [WARN]      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2016-01-03 13:40:07 [WARN]      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2016-01-03 13:40:07 [WARN]      at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
2016-01-03 13:40:07 [WARN]      at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
2016-01-03 13:40:07 [WARN]      at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
2016-01-03 13:40:07 [WARN]      at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
2016-01-03 13:40:07 [WARN]      at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
2016-01-03 13:40:07 [WARN]      at java.lang.Thread.run(Thread.java:745)

**Comment by greatman** [comment]
Seems to be missing the top line in your stacktrace. The one that says a SQL exception occured.

**Comment by Buckmanfu** [comment]
found it... there is a wall of text between this line and the top line I posted which is the query being sent. 
if need be I can give you that too

2016-01-03 13:40:06 [INFO] [Craftconomy3] Amount of accounts found:1413
2016-01-03 13:40:07 [WARN] org.h2.jdbc.JdbcSQLException: Scalar subquery contains more than one row; SQL statement:

also if it's important... 
Spigot version: git-Spigot-db6de12-18fbb24
CraftConomy3 3.3

**Comment by greatman** [comment]
Hmm, that error usually means it got 2 times the same username. Would it be possible to get a copy of your essential userdata folder in a zip?

**Comment by Buckmanfu** [comment]
I have to talk to the server owner and see what we can do.  I don't see any issues with sending you the data though.  I could take a couple days to arrange though since I will not be working on it tonight.

**Comment by Buckmanfu** [comment]
Just sent you a PM on your servers forums with the file attached

**Comment by Buckmanfu** [comment]
anything new on this?
